linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 150
  gocritic:
    settings:
      hugeParam:
        sizeThreshold: 256
      rangeValCopy:
        sizeThreshold: 256
    enabled-tags:
      - performance
      - style
      - experimental
      - opinionated
      - diagnostic

linters:
  enable:
    - govet
    - golint
    - gocyclo
    - maligned
    - goconst
    - misspell
    - lll
    - gocritic
  fast: false
  disable-all: false

run:
  timeout: 5m
  issues-exit-code: 1
  concurrency: 4
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - test

output:
  formats:
    - format: checkstyle
      path: report.xml
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
